### ISSUE TITLE
Will not actually launch fs-uae. ('runner class is None for <fsgs.platform.UnsupportedPlatform object>')

### ISSUE THREAD

**Issue by wyatt8740** [FrodeSolheim/fs-uae-launcher#78] opened 2020-01-18 07:10 UTC
```
START LOCAL GAME
x_missing_files 

Unhandled exception detected in thread MainThread:
  Exception:platform.py:get_runner:41

Traceback (most recent call last):
  File "/usr/local/share/fs-uae-launcher/fsui/qt/Button.py", line 18, in __clicked
    self.on_activated()
  File "/usr/local/share/fs-uae-launcher/launcher/ui/launch.py", line 89, in on_activated
    LauncherApp.start_game()
  File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 356, in start_game
    cls.start_local_game()
  File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 399, in start_local_game
    cls.start_local_game_other()
  File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 413, in start_local_game_other
    runner = platform_handler.get_runner(fsgs)
  File "/usr/local/share/fs-uae-launcher/fsgs/platform.py", line 41, in get_runner
    raise Exception("runner class is None for " + repr(self))
Exception: runner class is None for <fsgs.platform.UnsupportedPlatform object at 0x7f36735b40d0>


Unhandled exception detected in thread MainThread:
  Exception:platform.py:get_runner:41

Traceback (most recent call last):
  File "/usr/local/share/fs-uae-launcher/fsui/qt/Button.py", line 18, in __clicked
    self.on_activated()
  File "/usr/local/share/fs-uae-launcher/launcher/ui/launch.py", line 89, in on_activated
    LauncherApp.start_game()
  File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 356, in start_game
    cls.start_local_game()
  File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 399, in start_local_game
    cls.start_local_game_other()
  File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 413, in start_local_game_other
    runner = platform_handler.get_runner(fsgs)
  File "/usr/local/share/fs-uae-launcher/fsgs/platform.py", line 41, in get_runner
    raise Exception("runner class is None for " + repr(self))
Exception: runner class is None for <fsgs.platform.UnsupportedPlatform object at 0x7f36735b40d0>

[IMAGES] ImageLoader.on_quit_signal
[IMAGES] ImageLoader.on_quit_signal
```
This has been happening for several months, during which time I have been using the CLI.

I run Debian Sid, fully up to date (python 3.8, though it also was happening in 3.7 and probably earlier too). I'm using sysvinit instead of systemd, if that matters, which it shouldn't. amd64, Nehalem-era intel. Built the git master from sources for both fs-uae and the launcher.

This is my config file i'm trying to use, as generated by fs-uae-launcher itself.
```
$ cat '/home/wyatt/Documents/FS-UAE/Configurations/1.fs-uae'
# FS-UAE configuration saved by FS-UAE Launcher
# Last saved: 2020-01-04 01:14:51

[fs-uae]
chip_memory = 512
fast_memory = 1024
floppy_drive_0 = $HOME/amiga/software/Workbench13.adf
hard_drive_0 = hd1
ntsc_mode = 1
```

Also, 'platform settings…' is grayed out in the GUI.

**Comment by FrodeSolheim** [comment] 2020-01-18 11:01
What FS-UAE Launcher are you using? The 2.8 one from Debian repos? If so, can you try with the 3.0.x version from fs-uae.net (should work fine on Debian as well)?

I cannot reproduce here with version 3.0.2 at least...

**Comment by wyatt8740** [comment] 2020-01-27 06:54
>What FS-UAE Launcher are you using? The 2.8 one from Debian repos? If so, can you try with the 3.0.x version from fs-uae.net (should work fine on Debian as well)?

No; as I said, I "built the git master from sources for both fs-uae and the launcher."

3.1.0dev.

**Comment by redpiller** [comment] 2020-03-10 06:04
Ok i need to confirm on this one:
both from the current master and i get:

> 
> Unhandled exception detected in thread MainThread:
>   Exception:platform.py:get_runner:41
> 
> Traceback (most recent call last):
>   File "/usr/local/share/fs-uae-launcher/fsui/qt/Button.py", line 18, in __clicked
>     self.on_activated()
>   File "/usr/local/share/fs-uae-launcher/launcher/ui/launch.py", line 89, in on_activated
>     LauncherApp.start_game()
>   File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 356, in start_game
>     cls.start_local_game()
>   File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 399, in start_local_game
>     cls.start_local_game_other()
>   File "/usr/local/share/fs-uae-launcher/launcher/launcherapp.py", line 413, in start_local_game_other
>     runner = platform_handler.get_runner(fsgs)
>   File "/usr/local/share/fs-uae-launcher/fsgs/platform.py", line 41, in get_runner
>     raise Exception("runner class is None for " + repr(self))
> Exception: runner class is None for <fsgs.platform.UnsupportedPlatform object at 0x7f514c07da20>
>

**Comment by FrodeSolheim** [comment] 2020-03-22 09:59
The version is master is somewhat broken at the moment. It probably works if you add `platform = Amiga` to custom config, or enable support for multiple platforms and choose Amiga in the platform dropdown box.

I don't recommend using the master branches for anything serious at the moment... too much work in progress...

**Comment by redpiller** [comment] 2020-03-22 22:09
> The version is master is somewhat broken at the moment. It probably works if you add `platform = Amiga` to custom config, or enable support for multiple platforms and choose Amiga in the platform dropdown box.
> 
> I don't recommend using the master branches for anything serious at the moment... too much work in progress...

Can confirm, everything's working now

**Comment by wyatt8740** [comment] 2020-03-23 04:32
Ah, thanks. That makes sense, I suppose. I'm so used to the master branch being recommended by some other projects these days… (I mean ffmpeg).

**Comment by FrodeSolheim** [comment] 2021-02-20 12:00
This should be fixed in the master branch (for quite some time now).

**Closed by FrodeSolheim** 2021-02-20 12:00 UTC
