### ISSUE TITLE
(2.7.8-dev) ROM files are erased from DB if update file scan is performed

### ISSUE THREAD

**Issue by apiraino** [FrodeSolheim/fs-uae-launcher#37] opened 2016-03-21 23:41 UTC
How to reproduce:
* fs-uae-launcher fresh start (no saved configuration)
* Import Kickstarts
* Perform Update File Database
* **bug**: ROM files configuration is lost

Expected behaviour: ROM files should only be updated using "Import Kickstarts"

**Comment by apiraino** [comment] 2016-03-21 23:42
@FrodeSolheim I'll fix this bug, ok?

**Comment by FrodeSolheim** [comment] 2016-03-22 00:05
Yes, please fix the bug if you can. Updating the file database is not supposed to remove the Kickstart files, because the Kickstarts directory is (supposed to be) always included in the file scanner directory list.

**Comment by FrodeSolheim** [comment] 2016-03-30 23:03
Hi, I am unable to reproduce this problem!

**Comment by apiraino** [comment] 2016-03-31 20:17
Hi @FrodeSolheim, one important thing I forgot to mention: in the "Update File Database" screen, I have explicitely removed the directory with my kickstarts:

![shot](https://cloud.githubusercontent.com/assets/6098822/14189020/898af20c-f78b-11e5-85cd-b5e42163e6a5.png)

The issue is caused by the table `file` in `Files.sqlite` that contains both configuration and kickstart files (and the label correctly says `Scan for Kickstarts, Files and Configurations`).

The ambiguity raises because I can import kickstarts also from another place ("Import kickstarts..."). 
The obvious workaround is to **never** remove the kickstart directory when import all files :-) I think the "Import kickstarts..." is somehow redundant. The "Update File Database" should do everything, also the Amiga Forever import and be named "Update Config and Kickstart files Database".

What do you think about that?

By the way, "Import kickstart..." is also broken because of this related issue:
- On first kickstart import, the table `file` in `Files.sqlite` is correctly populated
- I delete all kickstart files minus one
- Re-run kickstart import
- **bug** The table `file` in `Files.sqlite` is not updated, the old kickstart records stay there.
- Of course this doesn't happen if I run "Update File Database"

**Comment by FrodeSolheim** [comment] 2016-03-31 20:50
Yes, removing the kickstarts directory from the scan list will cause this problem. The user should be prevented from doing that in order to prevent the issue from occurring (same as with configurations). Should be fixed in https://github.com/FrodeSolheim/fs-uae-launcher/commit/3b2c1ff19635551e93ca77762b6a295e06d4070e.

I agree that the import kickstart dialog is somewhat redundant now, but I don't want to remove it quite yet.

Regarding the last bug you mentioned, I'm not sure what you mean happens. Do you mean that you get duplicate entries in the file database for the imported kickstart paths (until the update file database function is run)? If so, that should not really be a problem?

**Comment by apiraino** [comment] 2016-03-31 21:28
> Do you mean that you get duplicate entries in the file database for the imported kickstart paths (until the update file database function is run)? If so, that should not really be a problem?

Actually what I mean is that if you run "Import Kickstart..." it does not check whether a kickstart in the DB exists on the filesystem. Example:
- First run, 3 kicks are inserted into DB
- I delete one kick file
- Re-run "import kickstart"
- still find 3 records into the DB

Having everything into a single table (`file`) would force checksumming all the table records to find the "zombies" and _that_ would be burdersome.

I think that your fix is enough.

**Comment by FrodeSolheim** [comment] 2016-03-31 21:31
Yes, this function was simply not intended to remove "zombies", neither in the Kickstarts dir or any other dir. It's an import/copy function :)

(Of course, it *could* run a "cleanup" on the Kickstarts dir as well, after importing, but I don't consider it essential)

**Closed by FrodeSolheim** 2016-03-31 21:31 UTC
Labels: bug
